// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB82HCP7uu3tHSm01lorrIQfGhpMk2Hk10',
    appId: '1:1002291154522:web:caf725866a67bc3ab75263',
    messagingSenderId: '1002291154522',
    projectId: 'twitter-clone-distro3-demo',
    authDomain: 'twitter-clone-distro3-demo.firebaseapp.com',
    storageBucket: 'twitter-clone-distro3-demo.appspot.com',
    measurementId: 'G-V67VTJTY4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxCpfM4AzgnpxyBi7okNM-mFIo7Lxflfk',
    appId: '1:1002291154522:android:52d0f161f4d71c95b75263',
    messagingSenderId: '1002291154522',
    projectId: 'twitter-clone-distro3-demo',
    storageBucket: 'twitter-clone-distro3-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5i8Aeo-DVR_hQEcLKkQ_FPgOVVUGVPMM',
    appId: '1:1002291154522:ios:0ec67c1f67dba785b75263',
    messagingSenderId: '1002291154522',
    projectId: 'twitter-clone-distro3-demo',
    storageBucket: 'twitter-clone-distro3-demo.appspot.com',
    iosClientId: '1002291154522-217vqc2vl37223qadc2m6qlf2c8gi9c2.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5i8Aeo-DVR_hQEcLKkQ_FPgOVVUGVPMM',
    appId: '1:1002291154522:ios:9fca3e32f649066fb75263',
    messagingSenderId: '1002291154522',
    projectId: 'twitter-clone-distro3-demo',
    storageBucket: 'twitter-clone-distro3-demo.appspot.com',
    iosClientId: '1002291154522-mgm3sv4vn6rbgbbnf9iepomckda68gl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
